baseURL = "https://mlitwin.github.io/"
languageCode = "en-us"
title = "Matthew Litwin"
description = "Matthew Litwin"

[[module.imports]]
    path = "github.com/josephhutch/aether"
    # project theme

[params]
    brand = "Matthew David Litwin"
	description = "Matthew Litwin's personal site"
    headshotimg = "img/avatar.jpg"
    github = "https://github.com/mlitwin"
    linkedin = "https://www.linkedin.com/in/matthewlitwin/"
    rssinmenu = false

