graph TD
code["<div>code.tf</div><div>variables.tfvars</div>"]
state0[state.tfstate]
state_tmp[refreshed.tfstate]
state1[state.tfstate]
infrastructure0[infrastructure]
infrastructure1[infrastructure]
tf_refresh(( ))
tf_plan(( ))
tf_plan_out[plan.json]
tf_apply(( ))

code --> tf_refresh
state0 --> tf_refresh
infrastructure0 --> tf_refresh
tf_refresh -- refresh --> state_tmp
code --> tf_plan
state_tmp --> tf_plan
tf_plan -- plan --> tf_plan_out
tf_plan_out --> tf_apply
infrastructure0 --> tf_apply
tf_apply -- apply --> state1
tf_apply -- apply --> infrastructure1
